
INSERT INTO `backend_nest_casas`.`casa` (id, title, bedrooms, bathrooms, squarefeet, description, available, country, city, cp, price, comodidad, photo, categories, userId, images) values (1, 'Chalé', 2, 4, 4887, 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit', true, 'España', 'Madrid', '06175', 787, 'tennis court', 'https://img.freepik.com/foto-gratis/piscina_74190-2104.jpg', '[1]', 1, '[{}]');
INSERT INTO `backend_nest_casas`.`casa` (id, title, bedrooms, bathrooms, squarefeet, description, available, country, city, cp, price, comodidad, photo, categories, userId, images) values (2, 'Loft', 2, 4, 7835, 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', false, 'España', 'Valladolid', '56883', 551, 'sauna', 'https://a0.muscache.com/im/pictures/b7756897-ef31-4080-b881-c4c7b9ec0df7.jpg?im_w=1440', '[1]', 2, '[{}]');
INSERT INTO `backend_nest_casas`.`casa` (id, title, bedrooms, bathrooms, squarefeet, description, available, country, city, cp, price, comodidad, photo, categories, userId, images) values (3, 'Cabana', 2, 4, 9045, 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', false, 'España', 'Sevilla', '75499', 821, 'sauna', 'https://a0.muscache.com/im/pictures/miso/Hosting-872254228905543887/original/2d5f7155-7458-4eb9-a7d3-753863d9eb45.jpeg?im_w=1200', '[2]', 3, '[{}]');
INSERT INTO `backend_nest_casas`.`casa` (id, title, bedrooms, bathrooms, squarefeet, description, available, country, city, cp, price, comodidad, photo, categories, userId, images) values (4, 'Loft', 1, 3, 540, 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', true, 'España', 'Palma de Mallorca', '47550', 664, 'gym', 'https://a0.muscache.com/im/pictures/miso/Hosting-872254228905543887/original/2d5f7155-7458-4eb9-a7d3-753863d9eb45.jpeg?im_w=1200', '[1]', 4, '[{}]');
INSERT INTO `backend_nest_casas`.`casa` (id, title, bedrooms, bathrooms, squarefeet, description, available, country, city, cp, price, comodidad, photo, categories, userId, images) values (5, 'Apartamento', 5, 4, 539, 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor', false, 'España', 'Murcia', '23680', 914, 'car wash', 'https://a0.muscache.com/im/pictures/prohost-api/Hosting-886115183611381927/original/864fbedf-f063-4406-b683-d98438d4db6e.jpeg', '[3]', 5, '[]');

​
INSERT INTO `backend_nest_casas`.`casa` (`title`, `bedrooms`, `bathrooms`, `squarefeet`, `description`, `available`, `country`, `city`, `cp`, `price`, `comodidad`, `photo`, `images`) VALUES ('casa1', '23', '23', '23', 'sdfvsd', '1', 'fdsfd', 'sdfsdf', '344', '1231', 'sdfsdf', 'sdsdf', 'sdfsdf');
INSERT INTO `backend_nest_casas`.`casa` (`title`, `bedrooms`, `bathrooms`, `squarefeet`, `description`, `available`, `country`, `city`, `cp`, `price`, `comodidad`, `photo`, `images`) VALUES ('casa2', '23', '23', '23', 'sdfvsd', '1', 'fdsfd', 'sdfsdf', '344', '1231', 'sdfsdf', 'sdsdf', 'sdfsdf');
INSERT INTO `backend_nest_casas`.`casa` (`title`, `bedrooms`, `bathrooms`, `squarefeet`, `description`, `available`, `country`, `city`, `cp`, `price`, `comodidad`, `photo`, `images`) VALUES ('casa3', '23', '23', '23', 'sdfvsd', '1', 'fdsfd', 'sdfsdf', '344', '1231', 'sdfsdf', 'sdsdf', 'sdfsdf');
INSERT INTO `backend_nest_casas`.`casa` (`title`, `bedrooms`, `bathrooms`, `squarefeet`, `description`, `available`, `country`, `city`, `cp`, `price`, `comodidad`, `photo`, `images`) VALUES ('casa4', '23', '23', '23', 'sdfvsd', '1', 'fdsfd', 'sdfsdf', '344', '1231', 'sdfsdf', 'sdsdf', 'sdfsdf');


INSERT INTO `backend_nest_casas`.`user` (`email`, `bio`, `phone`, `idioma`, `code`, `city`, `street`, `photo`, `role`, `fullName`) VALUES ('user1@gmail.com', 'sdfsdf', '2342343', 'spanish', 'dssdcsdc', 'cascsd', 'dscsdc', 'sdcscsd', 'user', 'sdcfsad');
INSERT INTO `backend_nest_casas`.`user` (`email`, `bio`, `phone`, `idioma`, `code`, `city`, `street`, `photo`, `role`, `fullName`) VALUES ('user1@gmail.com', 'sdfsdf', '2342343', 'spanish', 'dssdcsdc', 'cascsd', 'dscsdc', 'sdcscsd', 'user', 'sdcfsad');
